# Generated by Django 5.1.1 on 2025-07-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_customuser_options_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Группы к которым принадлежит пользователь', related_name='custom_users', related_query_name='user', to='auth.group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Специальные права для пользователя', related_name='custom_users', related_query_name='user', to='auth.permission', verbose_name='Права пользователя'),
        ),
    ]
