# Generated by Django 5.1.1 on 2025-07-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.IntegerField(default=None, verbose_name='Рейтинг'),
        ),
    ]
